### ISSUE TITLE
Title Customization

### ISSUE THREAD

**Issue by GijsVK94** [amidaware/tacticalrmm#1135] opened 2022-05-16 10:14 UTC
I would like be able to change some personal things to the RMM service.
Like the name of the login screen or the title of the tab in the browser or the icon.
![Login](https://user-images.githubusercontent.com/70382686/168571052-21df3e61-ab82-40c3-b77e-845972b4ecf7.png)
![Tab](https://user-images.githubusercontent.com/70382686/168571055-25a3a21c-3dad-4123-a95e-e1a020ab7bc9.png)

**Comment by dinger1986** [comment] 2022-05-16 10:15
duplicate of #463

**Closed by dinger1986** 2022-05-16 10:15 UTC
