### ISSUE TITLE
Client and Site local URL actions 

### ISSUE THREAD

**Issue by ninjamonkey198206** [amidaware/tacticalrmm#1067] opened 2022-04-15 15:10 UTC
**Is your feature request related to a problem? Please describe.**
While working on Grafana dashboards and integration, we came across several issues, two being bandwidth concerns and being able to sort out agents per site.

**Describe the solution you'd like**
The option to add unique URL actions to Clients and Sites, rather than just globally, could allow for a much wider range of options for integration, as well as potentially reducing bandwidth requirements since data wouldn't necessarily need to be streamed to a single destination, and could be stored and served local at the site until a connection is made to the service.

**Describe alternatives you've considered**
Federation, cloud based, etc, all of which present issues with bandwidth consumption and data storage.

**Additional context**

**Comment by sadnub** [comment] 2022-04-17 02:49
Duplicate of this: https://github.com/amidaware/tacticalrmm/issues/746

**Closed by sadnub** 2022-04-17 02:49 UTC
Labels: enhancement
