### ISSUE TITLE
SAML Support for Single Sign-On (such as Azure AD or Google or ADFS)

### ISSUE THREAD

**Issue by spanishdexter** [amidaware/tacticalrmm#1382] opened 2022-12-20 04:37 UTC
Just wanted to say I love what you guys have built it's awesome, but one question. Is there any chance of adding SAML support (SSO with something like Azure AD) in the future for logging into TRMM? 

It would be nice to use the same credentials and login process through an existing IDP like Azure AD in some environments already setup for it, for single sign on, instead of directly creating accounts in TRMM separately.

**Comment by silversword411** [comment] 2022-12-20 05:01
Dupe of https://github.com/amidaware/tacticalrmm/issues/508

**Closed by silversword411** 2022-12-20 05:01 UTC
