### ISSUE TITLE
Network scan

### ISSUE THREAD

**Issue by gkyriacou23** [amidaware/tacticalrmm#1132] opened 2022-05-15 10:50 UTC
A good feature would be, to be able to assign a device(workstation or server) as a probe and be able to discover all the devices in the network and import them(choice to install the agent).

**Comment by silversword411** [comment] 2022-05-15 11:40
Dinger made a script for that...check the script library

**Comment by NiceGuyIT** [comment] 2023-08-09 12:15
Possible duplicate of #112: Feature Request: Network scanning with installed agents

**Closed** 2023-08-09 12:33 UTC
Labels: enhancement
