### ISSUE TITLE
Browser token expiration not Work

### ISSUE THREAD

**Issue by thytetgc** [amidaware/tacticalrmm#1544] opened 2023-06-24 15:04 UTC
**Server Info:**
 - OS: [Ubuntu 20.04]
 - Browser: [chrome]
 - RMM Version (v0.15.12):

**Installation Method:**
  - [X] Standard

**Describe the bug**
After doing the alteration as described:

https://docs.tacticalrmm.com/functions/settings_override/#browser-token-expiration

Set up for 1 day, more continuous without needing to do a new login after a few days using.

I specify that after no more than 1 hour is possible, the web session expires, and request new access.

**Comment by wh1te909** [comment] 2023-06-28 02:19
Hi can you please post your `REST_KNOX` config

**Comment by wh1te909** [comment] 2023-07-30 20:23
please re-open once you provide your config, closing for now as cannot reproduce

**Closed by wh1te909** 2023-07-30 20:23 UTC
