### ISSUE TITLE
Custom script for alert system

### ISSUE THREAD

**Issue by clanto007** [amidaware/tacticalrmm#1443] opened 2023-02-25 07:45 UTC
**Is your feature request related to a problem? Please describe.**
Now the altert system is only with email and SMS.

**Describe the solution you'd like**
Such as Zabbix give the possibility to create customized alert systems with script, so when there is an alert Tactical will run this script.
In this manner everyone can add his custmized notification system without the needing of an exernal script that call tactical to know if it's all right.
So I can create customized notifications, for exemple a customer will receive a notify on telegram, another customer on another telegram and another one on his grafana for exemple, all create in TacticalRMM without creating external software that contact Tactical API.

**Describe alternatives you've considered**
If I use API to see alterts I need a system or a script out of Tactical that is always contacting TacticalRMM to see new alerts.
If I use script manager to create a script to do an alert on a client the alert is sent from the client, so if the client is for exemple offline I will not receive the notifications.

**Additional context**
Here the documentation of  Zabbix that do this:
https://www.zabbix.com/documentation/current/en/manual/config/notifications/media/script

**Comment by silversword411** [comment] 2023-02-25 13:55
Alert manager already has an option to run a script on trigger.

**Comment by clanto007** [comment] 2023-02-25 17:23
Where is this option?
I see scripts that can run on client, but not scripts that can run directly on server when there is the alert.
I can set to run ccleaner or bleachbit when the disk is nearly full, but I can't set a script that do an action with a script for exemple when client is offline. For this the server can only send email or SMS.

**Comment by wh1te909** [comment] 2023-02-25 20:55
so because server side alerts are not implemented yet, when you set a script to run as an alert action (either failure or resolved) it will pick the first online agent it finds. so even if the client is offline, trmm will find an online agent to run the script from you so still get the alert. eventually we will be making the script run on the server but for now this is how it works

**Comment by wh1te909** [comment] 2023-02-25 20:56
https://docs.tacticalrmm.com/functions/alerting/#action-settings

**Comment by silversword411** [comment] 2023-03-01 17:17
So....this is a duplicate of https://github.com/amidaware/tacticalrmm/issues/1316 as this is asking to run scripts server side.

**Closed by silversword411** 2023-03-01 17:17 UTC
