### ISSUE TITLE
Bulk edit devices

### ISSUE THREAD

**Issue by ithddean** [amidaware/tacticalrmm#2032] opened 2024-10-16 19:50 UTC
**Is your feature request related to a problem? Please describe.**
We have clients in different time zones. I found myself today updating multiple devices timezones one by one

**Describe the solution you'd like**
the ability to be able to select multiple end points and bulk update a setting. For timezones this could also work as an option under site for each client.

**Comment by silversword411** [comment] 2024-10-16 19:54
Dupe of https://github.com/amidaware/tacticalrmm/issues/529
Closing

**Closed by silversword411** 2024-10-16 19:54 UTC
