### ISSUE TITLE
Mesh Central - Consent

### ISSUE THREAD

**Issue by Jurgens92** [amidaware/tacticalrmm#1838] opened 2024-04-16 08:05 UTC
Hi,

with the new Consent feature, I would like to request a feature where you can enable or disable this feature based on Workstations/Servers

in my case, I would like to have users gain access to servers without consent feature, however connecting to workstations they need to have it enabled

thanks

**Comment by Serenfo** [comment] 2024-04-16 08:19
Hi,

You can easily do it with two group on meshcentral one "Workstation" with consent option enable and one "Server" with no consent needed. Move device on specific group and you've your policy :)

**Comment by Jurgens92** [comment] 2024-04-16 08:23
that makes sense, 
i thought it would be possible this way, with just a bit of manual moving.

thanks for the feedback.

but it would make a great feature, where this can be setup within TRMM, and not mesh.

**Comment by dinger1986** [comment] 2024-04-23 11:00
duplicate of #1826 please add comments there

**Closed** 2024-04-24 06:45 UTC
