### ISSUE TITLE
phantom column appears in top table

### ISSUE THREAD

**Issue by bbrendon** [amidaware/tacticalrmm#1264] opened 2022-08-24 16:56 UTC
to reproduce
1. select client so only list of computers for one client appears
2. change filter to online agents 
3. sort by boot time column.
4. profit.

![image](https://user-images.githubusercontent.com/6364477/186477770-27978c4a-fa8d-482e-81cc-a8555e4b710f.png)

**Comment by silversword411** [comment] 2022-08-24 17:12
What am I missing, I don't see any extra column. 

There's empty area on the right...but that's because the columns size themselves automatically to the data in it. Since your description is short, you have lots of space available on the right.

**Comment by silversword411** [comment] 2022-08-24 17:13
If you notice as you scroll thru the agent list....you'll see the columns move occasionally when there's more data that the columns need to re-size to.

**Comment by wh1te909** [comment] 2022-08-24 17:22
@silversword411 there is an extra column being added that wasn't there in previous versions. this was caused by my hack to get the stuff from summary tab to be filtered in the search. i'll need to figure out another way

**Comment by wh1te909** [comment] 2023-03-20 14:10
fixed, will be in next release

**Closed** 2023-03-20 14:09 UTC
Labels: bug
