### ISSUE TITLE
Take Control is not working, asks for username and password

### ISSUE THREAD

**Issue by airton583** [amidaware/tacticalrmm#1814] opened 2024-03-28 04:30 UTC
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: chrome
 - RMM Version (as shown in top left of web UI): v0.18.0

**Installation Method:**
  - [x ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
Take Control is not working, asks for username and password

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by wh1te909** [comment] 2024-03-28 05:54
please paste in your `/meshcentral/meshcentral-data/config.json` here (redact sensitive info)

**Comment by rasmatbe** [comment] 2024-03-28 06:21
Got the same behaviour with usernames formatted as email adresses. Once the @domain has been removed from username, the users are synced to Mesh and the remote control windows is working as intended

**Comment by myde2001** [comment] 2024-03-28 14:30
same problem

**Comment by dinger1986** [comment] 2024-03-28 14:31
> same problem

so you are also using an email address?

**Comment by myde2001** [comment] 2024-03-28 14:34
![image](https://github.com/amidaware/tacticalrmm/assets/93825819/7d1c8e95-a1bb-46d6-a380-035af191ee0d)

This is my Tactical users list

**Comment by dinger1986** [comment] 2024-03-28 14:42
is mesh installed on the same server? any other characters in the username?

**Comment by myde2001** [comment] 2024-03-28 14:45
> is mesh installed on the same server? any other characters in the username?

Yes, installed on the same server, previous installation that was updated through the script.
If I disable the "Sync Mesh Perms with TRMM" the remote control (and other meshcentral features) works again.
Only regular characters in the usernames.

**Comment by davidebonavita** [comment] 2024-03-28 15:14
Have the users been created in Mesh by Tactical once you enabled "Sync Mesh Perms with TRMM". I have the same issue and it looks like the list of autogenerated users in Mesh doesn't populate automatically

**Comment by dinger1986** [comment] 2024-03-28 15:17
have you checked using this? https://docs.tacticalrmm.com/mesh_integration/#get-a-url-to-login-to-mesh-as-the-mesh-superuser

**Comment by myde2001** [comment] 2024-03-28 15:18
> Have the users been created in Mesh by Tactical once you enabled "Sync Mesh Perms with TRMM"?. I have the same issue and it looks like the list of autogenerated users in Mesh doesn't populate automatically

No, they don't generate

**Comment by davidebonavita** [comment] 2024-03-28 15:44
> have you checked using this? https://docs.tacticalrmm.com/mesh_integration/#get-a-url-to-login-to-mesh-as-the-mesh-superuser

I'm able to login in Mesh as the defaul admin user with the generated link. 
I've tried to force update Tactical and reboot the server, but still the users are not created in Mesh.
I don't know if there are any logs I can check for the changes TRMM applies when you enable/disable the mesh integration?

**Comment by wh1te909** [comment] 2024-03-28 16:16
Run these 2 commands to turn on debug logging, turn mesh sync back on and then wait a few minutes and check the log file at `/rmm/api/tacticalrmm/tacticalrmm/private/log/trmm_debug.log`

```bash
echo "TRMM_LOG_LEVEL = 'DEBUG'" | tee --append /rmm/api/tacticalrmm/tacticalrmm/local_settings.py >/dev/null

sudo systemctl restart rmm celery celerybeat
```

**Comment by davidebonavita** [comment] 2024-03-28 16:29
> /rmm/api/tacticalrmm/tacticalrmm/private/log/trmm_debug.log

I only see a quite long of requests similar to
```[28/Mar/2024 16:23:13] INFO [tasks.py:sync_mesh_perms_task:532] Adding ['user//davREDACTED___14', 'user//deaREDACTED___379', 'user//rtREDACTED___7', 'user//jjREDACTED___6', 'user//tactical___1'] to node//@5hbeR@tSY7FC6kei3DvtEUyRjaltovNNtXEkHGrLCl5nyZkangTtQWPGfq4mU9A
[28/Mar/2024 16:23:13] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'adddeviceuser', 'nodeid': 'node//@5hbeR@tSY7FC6kei3DvtEUyRjaltovNNtXEkHGrLCl5nyZkangTtQWPGfq4mU9A', 'usernames': ['davREDACTED___14', 'deaREDACTED___379', 'rtREDACTED___7', 'jjREDACTED___6', 'tactical___1'], 'rights': 72, 'remove': False, 'responseid': 'meshctrl'}
[28/Mar/2024 16:23:13] INFO [tasks.py:sync_mesh_perms_task:532] Adding ['user//davREDACTED___14', 'user//deaREDACTED___379', 'user//rtREDACTED___7', 'user//jjREDACTED___6', 'user//tactical___1'] to node//@5hbeR@tSY7FC6kei3DvtEUyRjaltovNNtXEkHGrLCl5nyZkangTtQWPGfq4mU9A
[28/Mar/2024 16:23:13] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'adddeviceuser', 'nodeid': 'node//@5hbeR@tSY7FC6kei3DvtEUyRjaltovNNtXEkHGrLCl5nyZkangTtQWPGfq4mU9A', 'usernames': ['davREDACTED___14', 'deaREDACTED___379', 'rtREDACTED___7', 'jjREDACTED___6', 'tactical___1'], 'rights': 72, 'remove': False, 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:532] Adding ['user//davREDACTED___14', 'user//deaREDACTED___379', 'user//rtREDACTED___7', 'user//jjREDACTED___6', 'user//tactical___1'] to node//mbL5FcBhIubZ0Q2Rj0eNicmdmSkOmgL0ThlqJ4EO7hR0BDAJYuMXmbwPGyODNWBu
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'adddeviceuser', 'nodeid': 'node//mbL5FcBhIubZ0Q2Rj0eNicmdmSkOmgL0ThlqJ4EO7hR0BDAJYuMXmbwPGyODNWBu', 'usernames': ['davREDACTED___14', 'deaREDACTED___379', 'rtREDACTED___7', 'jjREDACTED___6', 'tactical___1'], 'rights': 72, 'remove': False, 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:532] Adding ['user//davREDACTED___14', 'user//deaREDACTED___379', 'user//rtREDACTED___7', 'user//jjREDACTED___6', 'user//tactical___1'] to node//aP8aXy8GQQLYDU66FJHcIimWEybqF4nO78T6jSp45tWy$HQGdD3negKF6$z2Y2wD
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'adddeviceuser', 'nodeid': 'node//aP8aXy8GQQLYDU66FJHcIimWEybqF4nO78T6jSp45tWy$HQGdD3negKF6$z2Y2wD', 'usernames': ['davREDACTED___14', 'deaREDACTED___379', 'rtREDACTED___7', 'jjREDACTED___6', 'tactical___1'], 'rights': 72, 'remove': False, 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:532] Adding ['user//davREDACTED___14', 'user//deaREDACTED___379', 'user//rtREDACTED___7', 'user//jjREDACTED___6', 'user//tactical___1'] to node//@5hbeR@tSY7FC6kei3DvtEUyRjaltovNNtXEkHGrLCl5nyZkangTtQWPGfq4mU9A
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'adddeviceuser', 'nodeid': 'node//@5hbeR@tSY7FC6kei3DvtEUyRjaltovNNtXEkHGrLCl5nyZkangTtQWPGfq4mU9A', 'usernames': ['davREDACTED___14', 'deaREDACTED___379', 'rtREDACTED___7', 'jjREDACTED___6', 'tactical___1'], 'rights': 72, 'remove': False, 'responseid': 'meshctrl'}```

Followed by
```[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'users', 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:556] Display names don't match. Updating user//rtREDACTED___7 name from  to REDACTED
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'edituser', 'id': 'user//rtREDACTED___7', 'realname': 'REDACTED', 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:556] Display names don't match. Updating user//tactical___1 name from  to REDACTED
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'edituser', 'id': 'user//tactical___1', 'realname': 'REDACTED', 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:556] Display names don't match. Updating user//fjREDACTED___62 name from  to REDACTED - REDACTED
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'edituser', 'id': 'user//fjREDACTED___62', 'realname': 'REDACTED - REDACTED', 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:556] Display names don't match. Updating user//davREDACTED___14 name from  to REDACTED - REDACTED
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'edituser', 'id': 'user//davREDACTED___14', 'realname': 'REDACTED - REDACTED', 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:556] Display names don't match. Updating user//deaREDACTED___379 name from  to REDACTED - REDACTED
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'edituser', 'id': 'user//deaREDACTED___379', 'realname': 'REDACTED - REDACTED', 'responseid': 'meshctrl'}
[28/Mar/2024 16:24:11] INFO [tasks.py:sync_mesh_perms_task:556] Display names don't match. Updating user//jjREDACTED___6 name from  to REDACTED - REDACTED
[28/Mar/2024 16:24:11] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'edituser', 'id': 'user//jjREDACTED___6', 'realname': 'REDACTED - REDACTED', 'responseid': 'meshctrl'}```

**Comment by wh1te909** [comment] 2024-03-28 16:38
@davidebonavita post your redacted `/meshcentral/meshcentral-data/config.json`

**Comment by wh1te909** [comment] 2024-03-28 17:01
@davidebonavita remove the `nonalpha` requirement from  your `passwordRequirements`

**Comment by davidebonavita** [comment] 2024-03-28 17:04
> ```shell
> sudo systemctl restart rmm celery celerybeat
> ```

Well, that worked, thanks!

**Comment by wh1te909** [comment] 2024-03-28 17:13
@myde2001 I don't see anything obvious from your config that would cause it to break, please follow my instructions here to enable debug logging https://github.com/amidaware/tacticalrmm/issues/1814#issuecomment-2025602318

**Comment by wh1te909** [comment] 2024-03-28 17:14
@davidebonavita remove the `TRMM_LOG_LEVEL = 'DEBUG'` line that was added to the bottom of `/rmm/api/tacticalrmm/tacticalrmm/local_settings.py` and then restart the services again, this way your server doesn't fill up with debug logs as this file can get quite large

**Comment by myde2001** [comment] 2024-03-28 22:13
> @myde2001 I don't see anything obvious from your config that would cause it to break, please follow my instructions here to enable debug logging [#1814 (comment)](https://github.com/amidaware/tacticalrmm/issues/1814#issuecomment-2025602318)

`[24/Jan/2024 16:36:11] ERROR [tasks.py:_handle_task_on_agent:255] Unable to create scheduled task Obtener MeshCentral NodeId on DESKTOP-59DQ3QL: timeout
[28/Mar/2024 22:11:37] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'users', 'responseid': 'meshctrl'}
[28/Mar/2024 22:11:37] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'nodes', 'responseid': 'meshctrl'}
[28/Mar/2024 22:11:37] DEBUG [tasks.py:sync_mesh_perms_task:562] Traceback (most recent call last):
  File "/rmm/api/tacticalrmm/core/tasks.py", line 458, in sync_mesh_perms_task
    "node_id": f"node//{agent.hex_mesh_node_id}",
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/tacticalrmm/agents/models.py", line 457, in hex_mesh_node_id
    return _b64_to_hex(self.mesh_node_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/tacticalrmm/core/utils.py", line 128, in _b64_to_hex
    return b64encode(bytes.fromhex(h)).decode().replace(r"/", "$").replace(r"+", "@")
                     ^^^^^^^^^^^^^^^^
TypeError: fromhex() argument must be str, not None

[28/Mar/2024 22:12:00] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'users', 'responseid': 'meshctrl'}
[28/Mar/2024 22:12:00] DEBUG [mesh_utils.py:mesh_action:105] {'action': 'nodes', 'responseid': 'meshctrl'}
[28/Mar/2024 22:12:00] DEBUG [tasks.py:sync_mesh_perms_task:562] Traceback (most recent call last):
  File "/rmm/api/tacticalrmm/core/tasks.py", line 458, in sync_mesh_perms_task
    "node_id": f"node//{agent.hex_mesh_node_id}",
                        ^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/tacticalrmm/agents/models.py", line 457, in hex_mesh_node_id
    return _b64_to_hex(self.mesh_node_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/rmm/api/tacticalrmm/core/utils.py", line 128, in _b64_to_hex
    return b64encode(bytes.fromhex(h)).decode().replace(r"/", "$").replace(r"+", "@")
                     ^^^^^^^^^^^^^^^^
TypeError: fromhex() argument must be str, not None
`

**Comment by wh1te909** [comment] 2024-03-28 23:45
@myde2001 cool thanks, just pushed a fix for that. please run the following commands and then toggle sync back on and it will work:

```bash
wget -O /rmm/api/tacticalrmm/core/tasks.py https://raw.githubusercontent.com/amidaware/tacticalrmm/develop/api/tacticalrmm/core/tasks.py

wget -O /rmm/api/tacticalrmm/core/utils.py https://raw.githubusercontent.com/amidaware/tacticalrmm/develop/api/tacticalrmm/core/utils.py

sudo systemctl restart rmm celery celerybeat
```

**Comment by myde2001** [comment] 2024-03-29 00:05
> @myde2001 cool thanks, just pushed a fix for that. please run the following commands and then toggle sync back on and it will work:
> 
> ```shell
> wget -O /rmm/api/tacticalrmm/core/tasks.py https://raw.githubusercontent.com/amidaware/tacticalrmm/develop/api/tacticalrmm/core/tasks.py
> 
> wget -O /rmm/api/tacticalrmm/core/utils.py https://raw.githubusercontent.com/amidaware/tacticalrmm/develop/api/tacticalrmm/core/utils.py
> 
> sudo systemctl restart rmm celery celerybeat
> ```

Can confirm, now it's working

**Comment by wh1te909** [comment] 2024-03-29 08:43
> Got the same behaviour with usernames formatted as email adresses. Once the @Domain has been removed from username, the users are synced to Mesh and the remote control windows is working as intended

will be fixed in tomorrow's release

**Comment by wh1te909** [comment] 2024-03-29 21:11
all issues resolved in the latest release 0.18.1

**Closed by wh1te909** 2024-03-29 21:11 UTC

**Comment by sightkick** [comment] 2024-03-31 08:06
OK. I have the same problem. If I login in Tactical with user1 and then go to the mesh Instance it logs in with this user. If I once log out in mesh it won´t relogin.
If I change in tactical to user2 it leaves in mesh in user1 until I logout in mesh and couldn´t login new.Login is only possible with the mesh master user.

bug or feature :-)

Here is my debug info
´´´
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'users', 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'nodes', 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:495] Adding new user jkemke___14 to mesh
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adduser', 'username': 'jkemke___14', 'email': 'jkemke.0WmNF9@tacticalrmm-do-not-change-FTy03.local', 'pass': 'CZC!RGgPNvFbXnO5er6mFUSyUEY8DV', 'resetNextLogin': False, 'randomPassword': False, 'removeEvents': False, 'emailVerified': True, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'edituser', 'id': 'user//jkemke___14', 'realname': 'Jens Kemke - Holger Dansberg - sightkick', 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:495] Adding new user hdansberg___1 to mesh
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adduser', 'username': 'hdansberg___1', 'email': 'hdansberg.28ZvzL@tacticalrmm-do-not-change-qesVH.local', 'pass': 'Sdhwlc1HtIs2q8j!x5znjcg2Cn4VwX', 'resetNextLogin': False, 'randomPassword': False, 'removeEvents': False, 'emailVerified': True, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'edituser', 'id': 'user//hdansberg___1', 'realname': 'Holger Dansberg - Holger Dansberg - sightkick', 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//M537HqDzTNvQlR4z6K7VM2Ja49qY2p1F9Dm8HKf5ZD5YZvKIeAh9Erpzz7jXUsOx
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//M537HqDzTNvQlR4z6K7VM2Ja49qY2p1F9Dm8HKf5ZD5YZvKIeAh9Erpzz7jXUsOx', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//FKfgzEGjWv75Wjv7cZGyMxV9Hak0w8d398nA5SqHMyBY79UVzQQOzucr2QXmLizd
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//FKfgzEGjWv75Wjv7cZGyMxV9Hak0w8d398nA5SqHMyBY79UVzQQOzucr2QXmLizd', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//816SiOmL3G4tHp0gcdGFWb8dOqe@oeEiQPDURmAUgrVyVK@wPMDk$yi9GJDAzaiK
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//816SiOmL3G4tHp0gcdGFWb8dOqe@oeEiQPDURmAUgrVyVK@wPMDk$yi9GJDAzaiK', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//dG@kBqkNa0Y@neo7u8Qd3B9afS21JKn1Yp9t7ToZKrAMutY329J@EBSu@Pixh9e2
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//dG@kBqkNa0Y@neo7u8Qd3B9afS21JKn1Yp9t7ToZKrAMutY329J@EBSu@Pixh9e2', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//xDABS27VlYgbzPMIDeGj9NiPtxFTg$bxau$7dZP6EIBM$tsY8WXbPj9W7Ag4BITX
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//xDABS27VlYgbzPMIDeGj9NiPtxFTg$bxau$7dZP6EIBM$tsY8WXbPj9W7Ag4BITX', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//kAKdnHG4YbSF@nrz9AUZdFMYZP4OucboAyBA8JSDnt1ciwcBhwZ8OmQDjUgj8dTq
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//kAKdnHG4YbSF@nrz9AUZdFMYZP4OucboAyBA8JSDnt1ciwcBhwZ8OmQDjUgj8dTq', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//7o129e@YKk@6kUnBW1DEDH8PTYZFThwXkQB2lMniOxFcWVy9K0E9XvVPMObfohNO
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//7o129e@YKk@6kUnBW1DEDH8PTYZFThwXkQB2lMniOxFcWVy9K0E9XvVPMObfohNO', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//t6MFbjs5X5cmjytq7hpdT4fzi5nlLvdFx5nOZXlIsH6NG$zv56khlwbSmUeu9AP5
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//t6MFbjs5X5cmjytq7hpdT4fzi5nlLvdFx5nOZXlIsH6NG$zv56khlwbSmUeu9AP5', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//CGwTSkmAHEXh4rG@Cci@CqiqMsexAceNeovGAoLcyHrpYJFb4kjQ7Uatxm9HssYo
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//CGwTSkmAHEXh4rG@Cci@CqiqMsexAceNeovGAoLcyHrpYJFb4kjQ7Uatxm9HssYo', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//Bm8yIsSS4ZA2Bh1D9tnuF1zY8VgccuLMkbCerS@0$28BbPDqGnFEjOAmaRWa2dW8
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//Bm8yIsSS4ZA2Bh1D9tnuF1zY8VgccuLMkbCerS@0$28BbPDqGnFEjOAmaRWa2dW8', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//U1UbSeYdlabucwOv6wzHtfkqfOjcf3i2Xg9GU8s0oBUk7h90j2GYIqkkP2q7AVot
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//U1UbSeYdlabucwOv6wzHtfkqfOjcf3i2Xg9GU8s0oBUk7h90j2GYIqkkP2q7AVot', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//Gd5xajqLcbUH4O0DXGrSv09h3paOrqYyz9@x3H@D2C$oRgPwMETsxx78LhIB5IeU
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//Gd5xajqLcbUH4O0DXGrSv09h3paOrqYyz9@x3H@D2C$oRgPwMETsxx78LhIB5IeU', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//ZlSixlPynxZX3jL9XD89ljyY$r$LcO8RbApjvq@mmHIXjcvT@h7MU@v3xabLJcqB
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//ZlSixlPynxZX3jL9XD89ljyY$r$LcO8RbApjvq@mmHIXjcvT@h7MU@v3xabLJcqB', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//ZS9TqTOC9mak4NqpiwYg3BhmVAsPVnz3DDyUVB2Xzu1bNa5Auandtex6UU9hPAiP
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//ZS9TqTOC9mak4NqpiwYg3BhmVAsPVnz3DDyUVB2Xzu1bNa5Auandtex6UU9hPAiP', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//T4rJO$jnllT5inW@rUunLEw0K5E$@kCt@MnfD8ojXMiUSpjzEO9sz3SpjVgyTjQF
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//T4rJO$jnllT5inW@rUunLEw0K5E$@kCt@MnfD8ojXMiUSpjzEO9sz3SpjVgyTjQF', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//NKnOP2YxcUcXU3FMkzCYfTp4yzUrElnfPk37NNGsrl$eyBoE2UJMj@1kofTM$KJE
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//NKnOP2YxcUcXU3FMkzCYfTp4yzUrElnfPk37NNGsrl$eyBoE2UJMj@1kofTM$KJE', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//VL2XDM0NfPQux44Fub2iB3uhH7Vr3DOnzu41X0qmEAmV0r$rdTLVeOhx9v7WyVcr
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114] {'action': 'adddeviceuser', 'nodeid': 'node//VL2XDM0NfPQux44Fub2iB3uhH7Vr3DOnzu41X0qmEAmV0r$rdTLVeOhx9v7WyVcr', 'usernames': ['jkemke___14', 'hdansberg___1'], 'rights': 3563736, 'remove': False, 'responseid': 'meshctrl'}
[31/Mar/2024 07:38:00] INFO [tasks.py:sync_mesh_perms_task:536] Adding ['user//jkemke___14', 'user//hdansberg___1'] to node//HDW$rjUkoLW0IofD2x1C6wcOhvlcB2rqQ1RyKzzjdOMgFZBSfNEVd8gwzelLSmv8
[31/Mar/2024 07:38:00] DEBUG [mesh_utils.py:mesh_action:114]

´´´

this is my mesh config.json file
´´´
{
  "settings": {
    "cert": "mesh.domain.de",
    "WANonly": true,
    "minify": 1,
    "port": 4430,
    "aliasPort": 443,
    "redirPort": 800,
    "allowLoginToken": true,
    "allowFraming": true,
    "_agentPing": 60,
    "agentPong": 300,
    "allowHighQualityDesktop": true,
    "tlsOffload": "127.0.0.1",
    "agentCoreDump": false,
    "compression": true,
    "wsCompression": true,
    "agentWsCompression": true,
    "maxInvalidLogin": {
      "time": 5,
      "count": 5,
      "coolofftime": 30
    },
    "postgres": {
      "user": "exampleuser",
      "password": "abcde",
      "port": "5432",
      "host": "localhost"
    }
  },
  "domains": {
    "": {
      "title": "Tactical RMM",
      "title2": "Tactical RMM",
      "newAccounts": false,
      "certUrl": "https://mesh.domain.de:443/",
      "geoLocation": true,
      "cookieIpCheck": false,
      "mstsc": true
    }
  }
}
´´´

**Comment by silversword411** [comment] 2024-03-31 08:53
You have to log out of Tactical and mesh if you're going to be using the same browser to test switching users.

If you're just testing permissions have one user in browser and another in invognito

**Comment by sightkick** [comment] 2024-03-31 09:40
If I logout in normal browser in TRMM and mesh, and relogin as another user in trmm, mesh asks for credentials.
Does it have a delay when "autologin" is able to use? 
When I login in normal browser after a fews minutes in trmm and mesh, mesh logs in automatical. 
If I login in inccognito mode in TRMM and the open mesh it prompts for credentials. Everytime
Weird...
