### ISSUE TITLE
Disk checks based on remaining space rather than just percentage.

### ISSUE THREAD

**Issue by scoopdreams** [amidaware/tacticalrmm#1328] opened 2022-10-25 02:12 UTC
Hi is there a way for checks to monitor based on disk space (e.g <30GB) rather than percentage.

Our servers and workstations have varied disk space and a percentage based check might not equate to actionable urgency (e.g 10% of 1TB vs 10% of 250GB).

**Comment by wh1te909** [comment] 2022-10-25 06:52
duplicate of https://github.com/amidaware/tacticalrmm/issues/255 for now you can just write a script check to do this, if you need help ask in scripts channel in discord and I can write one for you or might already be one in community scripts

**Closed by wh1te909** 2022-10-25 06:52 UTC
