### ISSUE TITLE
[BUG] Remote background process cpu usage sorting not working

### ISSUE THREAD

**Issue by P6g9YHK6** [amidaware/tacticalrmm#1859] opened 2024-04-26 11:17 UTC
**Server Info (please complete the following information):**
 - OS: Debian 12
 - Browser: FF
 - RMM Version (as shown in top left of web UI): 0.18.2

**Installation Method:**
  - [x] Standard
  - [ ] Standard with `--insecure` flag at install
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):v2.7.0 
- Agent OS: [e.g. Win 10 v2004, Server 2016] Windows server 2022

**Describe the bug**
CPU is not ordered properly when ordering from biggest to smallest and vice-versa

**To Reproduce**
1. Go to processes
2. Click on cpu

**Expected behavior**
it should sort the cpu usage as expected

**Screenshots**
![image](https://github.com/amidaware/tacticalrmm/assets/17877371/13d0f036-5618-4fd7-9259-4620f0b1f9e7)

![image](https://github.com/amidaware/tacticalrmm/assets/17877371/620c71ec-31d1-4e19-adf5-0a1d25005bca)

**Comment by NiceGuyIT** [comment] 2024-04-26 18:36
Duplicate of #1445

**Closed** 2024-04-27 00:34 UTC
