### ISSUE TITLE
Feature Request: Custom Script Repository

### ISSUE THREAD

**Issue by SoarinFerret** [amidaware/tacticalrmm#1309] opened 2022-10-10 14:26 UTC
**Is your feature request related to a problem? Please describe.**
Manually uploading and/or editing scripts on the web interface is frustrating, plus we don't get to see long-term changes. We have some scripts we use that talk to our own servers to pull down software for custom installations that we would rather not be on the community script repository. These scripts are already maintained in a private git repository, it would be nice if we could add our own repository behind some basic authentication

**Describe the solution you'd like**
The ability to add our own multiple repositories with for scripts. Preferably these repos would have the option of being pulled down in an authenticated fashion so we do not have to open the scripts to the public. I don't mind updating our repository to mirror the format located on the TRMM community script repo.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dinger1986** [comment] 2022-10-10 14:36
duplicate of #1206

**Closed by dinger1986** 2022-10-10 14:36 UTC
